language: php
php:
  - 5.5
notifications:
  webhooks:
    - webhook: https://future500.slack.com/services/hooks/incoming-webhook?token=CckepAuyRJ3lxrT371bFxnOX
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - composer self-update
  - composer install --dev --no-scripts --prefer-source --no-interaction
  - bower install
  - npm install
  - grunt
script:
  - bin/phpspec run
