language: php
php:
  - 5.5
notifications:
  slack:
    rooms:
      - "future500:D25FmdODmv6meSORkbgp91eA#poolz"
    on_success: always
    on_failure: always
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - composer self-update
  - composer install --dev --no-scripts --prefer-source --no-interaction
  - bower install
  - npm install
  - grunt
script:
  - bin/phpspec run
