debug: %debug%

console.name:    Future CI
console.version: 0.0.1

monolog.logfile: %root_dir%/var/logs/app.dev.log
monolog.level:   debug
monolog.name:    F500ci

slack.username: %slack.username%
slack.token:    %slack.token%

filesystem.class: F500\CI\Filesystem\Filesystem

f500ci.suites_dir: %root_dir%/var/suites
f500ci.builds_dir: %root_dir%/var/builds

f500ci.renderer.view_dir: %root_dir%/app/views
